Form.Examples/Controllers/ExamplesController.cs
using Form.Examples.Models;
using Form.Examples.Utils;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Form.Examples.Controllers
{
    public class ExamplesController : Controller
    {
        #region EXAMPLE ONE
        // Example One - No Validation Summary
        public ActionResult ExampleOne()
        {
            return View();
        }

        // Example One - Validation Summary        
        public ActionResult ExampleOneB()
        {
            return View();
        }

        // Example One - highlight input fields Rendered
        public ActionResult ExampleOneC()
        {
            return View();
        }

        // Example One - highlight input fields Javascript
        public ActionResult ExampleOneD()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ExampleOne(ExampleOneViewModel model)
        {
            //The entire ModelState is checked by data annotations. Check the class ExampleOneViewModel for the data annotations.
            if (ModelState.IsValid)
            {
                model.Insert();
                return View("Completed");
            }
            else
            {
                //The Request.UrlReferrer object contains the info about the previous page visited.
                //The Segments contains the segments of the previous page visited, and the last one contains the view that submitted the form.
                //Retrieve the last segment and use it to return to the correct view.
                string view = Request.UrlReferrer.Segments.Last();
                return View(view, model);
            }
        }
        #endregion

        #region EXAMPLE TWO

        public ActionResult ExampleTwo()
        {
            return View();
        }

        public ActionResult ExampleTwoForm()
        {
            //return the form for the modal.
            return View("_ExampleTwoForm");
        }

        [HttpPost]
        public ActionResult ExampleTwo(ExampleTwoViewModel model)
        {
            try
            {
                //The entire ModelState is checked by data annotations. Check the class ExampleTwoViewModel for the data annotations.
                if (ModelState.IsValid)
                {
                    return Json("OK");
                }
                else
                {
                    return View("_ExampleTwoForm", model);
                }
            }
            catch
            {
                return Json("KO");
            }
        }

        #endregion

        #region EXAMPLE THREE

        public ActionResult ExampleThree()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ExampleThree(ExampleThreeViewModel model)
        {
            //The entire ModelState is checked by data annotations. Check the class ExampleThreeViewModel for the data annotations.
            if (ModelState.IsValid)
            {
                //Import the file in a folder inside the solution.
                model.ImportFile();
                return View("Completed");
            }
            else
                return View(model);
        }

        public ActionResult ExampleThreeB()
        {
            return View();
        }

        [HttpPost]
        //The FormCollection is used to differ the get and post call.
        public ActionResult ExampleThreeB(FormCollection collection)
        {
            //The Request object contains data about the post. It contains also the list of the file passed to the controller.
            foreach (string ind in Request.Files)
            {
                //Save the current file in a HttpPostedFileBase.
                HttpPostedFileBase hpf = Request.Files[ind] as HttpPostedFileBase;
                //if the content lenght of the file is zero means either the file is empty or no file has been chosen.
                if (hpf.ContentLength == 0)
                    //return to the View
                    return View();
                //Upload the file as in the ExampleThreeViewModel ImportFile() method.
                Tools.UploadFile(hpf);
            }
            return View("Completed");

        }

        #endregion

        #region EXAMPLE FOUR

        public ActionResult ExampleFour()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ExampleFour(ExampleFourViewModel model)
        {
            if (ModelState.IsValid)
            {
                return View("Completed");
            }
            else
                return View(model);
        }

        #endregion

        #region EXAMPLE FIVE

        public ActionResult ExampleFive()
        {
            ExampleFiveViewModel model = new ExampleFiveViewModel();
            //The Init() method add data in the Invoices attribute. The Invoices attribute is rendered as drop down list in the view.
            model.Init();
            return View(model);
        }
        
        [HttpPost]
        public ActionResult ExampleFive(ExampleFiveViewModel model)
        {
            //gather mockup data for the partial view.
            model.GetData();
            return PartialView("_ExampleFiveResult", model);
        }

        #endregion


        //View for completed operation.
        public ActionResult Completed()
        {
            return View();
        }
    }
}

Form.Examples/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Form.Examples.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Form.Examples/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Form.Examples/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Form.Examples/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Form examples</h1>
    <h2>By: Matteo Innocenti (<a href="mailto:minnocenti87@gmail.com">minnocenti87@gmail.com</a>)</h2>
    <p class="lead">This project show various implementations of forms. Every implementation is fully documented and commented step by step. You can reach the examples from the navigation bar and from the links below.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Example 1</h2>
        <p>
            Subscription form mockup.
        </p>
        <div class="list-group">
            @Html.ActionLink("No Validation Summary", "ExampleOne", "Examples", null, new { @title = "No Validation Summary", @class = "list-group-item list-group-item-action" })
            @Html.ActionLink("Validation Summary", "ExampleOneB", "Examples", null, new { @title = "Validation Summary)", @class = "list-group-item list-group-item-action" })
            @Html.ActionLink("Highlight input fields - RENDERED", "ExampleOneC", "Examples", null, new { @title = "Highlight input fields - RENDERED", @class = "list-group-item list-group-item-action" })
            @Html.ActionLink("Highlight input fields - Javascript", "ExampleOneD", "Examples", null, new { @title = "Highlight input fields - Javascript", @class = "list-group-item list-group-item-action" })
        </div>
    </div>
    <div class="col-md-4">
        <h2>Example 2</h2>
        <p>
            Dialog form mockup.
        </p>
        <div class="list-group">
            @Html.ActionLink("Insert subscriber dialog", "ExampleTwo", "Examples", null, new { @title = "Insert subscriber dialog", @class = "list-group-item list-group-item-action" })
        </div>
    </div>
    <div class="col-md-4">
        <h2>Example 3</h2>
        <p>
            Import file form mockup.
        </p>
        <div class="list-group">
            @Html.ActionLink("Import file by Model", "ExampleThree", "Examples", null, new { @title = "Import file by Model", @class = "list-group-item list-group-item-action" })
            @Html.ActionLink("Import file by Request.Files", "ExampleThreeB", "Examples", null, new { @title = "Import file by Request.Files", @class = "list-group-item list-group-item-action" })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Example 4</h2>
        <p>
            WYSIWYG editor form mockup.
        </p>
        <div class="list-group">
            @Html.ActionLink("CKEditor form", "ExampleFour", "Examples", null, new { @title = "CKEditor form", @class="list-group-item list-group-item-action" })
        </div>
    </div>
    <div class="col-md-4">
        <h2>Example 5</h2>
        <p>
            Highcharts form mockup.
        </p>
        <div class="list-group">
            @Html.ActionLink("Highcharts form (Ajax form)", "ExampleFive", "Examples", null, new { @title = "Highcharts form (Ajax form)", @class = "list-group-item list-group-item-action" })
        </div>
    </div>
</div>